name: Build Rebuilt-NixOS ISO

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

env:
  NIX_CONFIG: experimental-features = nix-command flakes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rebuilt-NixOS
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build ISO
        run: nix build --accept-flake-config .#iso --print-build-logs

      - name: Show ISO
        run: ls -lh result/iso/

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: rebuilt-nixos-iso
          path: result/iso/*.iso
          if-no-files-found: error
